### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by czarnota** [chrisbazley/strb_t#1]
This looks great. I would be interested in using this code in one of my private projects, but there is no information about license.

**Comment by chrisbazley** [comment]
Sorry about that. I have since added a MIT licence. You are welcome to use the code. I'm happy if anyone finds my prototype useful.

I deliberately didn't include licence information because I didn't want WG14 to misunderstand my intent in writing N3250 and I wanted to avoid even the potential for legal issues. I hesitated about whether to write an implementation of strb_t at all, but did so to prove that implementations tailored for different kinds of platforms are practical, and to show the small code size required. In the end, it proved useful to assessing the cost of different features. However, since it is just a prototype, the code is not written in my customary style, nor documented and tested to the extent I would normally require.

I could have saved myself a lot of effort by writing a much shorter paper promoting my time-proven string buffer implementation, which you can find in https://github.com/chrisbazley/CBUtilLib. However, I felt that would have been a bit insulting to the committee and the importance of the topic. Of course, 'stringbuffer' and 'strb_t' are still somewhat similar, but I think that strb_t is nicer to use, more flexible, less error-prone, and a more powerful abstraction. Unfortunately, that is partly because strb_t uses reserved names.

I believe that most of the value of my proposed design lies in the interface, not its implementation (which is just a variation of something that has been written countless times before). However, in order to realise the full value of this interface, it would need to be part of the C standard (like malloc and free) in order to address any fears that might otherwise prevent programmers from relying upon it as a mechanism for interoperability between libraries.

It's interesting to compare the situation of strb_b with the Annex K string functions that have a '_s' suffix, which are in the C standard but are not provided by most vendors and also exist as a third party library. Uptake hasn't been high, from what I've seen. That's why I'm pushing for mandatory inclusion of strb_t in conforming implementations of C.
